### ISSUE TITLE
[bug] Can't run in terminal

### ISSUE THREAD

**Issue by yantze** [electron-modules/electrom#12]
screenshot:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/2226423/158996736-79b6b446-15bf-4ad0-bf49-6ed2462d1117.png">

```shell
npm i --save-dev electrom
./node_modules/.bin/electrom 100 
```

**Comment by yantze** [comment]
@xudafeng 感觉 bin 可以去掉了

**Comment by xudafeng** [comment]
@yantze 来个pr
