### ISSUE TITLE
a UI suggestion for new design

### ISSUE THREAD

**Issue by sriting** [electron-modules/electrom#20]
We hope to add `webContents` column back to the table.
The `webContents` column has been removed in [PR 15](https://github.com/electron-modules/electrom/pull/15) (as shown in the following picture), which cause complicated operations.
For example, when we want to open a devtool of a `webview` or a specific `BrowserWindow`, we can directly find the process by the content of `webContents` in the old design. However, we need to click each `process` and click the `webContents` tab to see the detail in order to find the process and open the devtool, which is much more complex than the old design.
![image](https://user-images.githubusercontent.com/17586742/164145607-f415f29d-7607-4744-8065-b77caf65d1f2.png)
Hope to improve this issue.

**Comment by xudafeng** [comment]
中文就行

**Comment by yantze** [comment]
可以的，感觉可以把这个拆分成两个， devtool 和 more，more 菜单提供 kill 能力。 devtool 主要是方便点击。 more 里面使不常用的动作
